done node hw2
Leonidowicz/nodejs-homework-02 pull request #1
Opened 2021-11-28 15:50 UTC by Leonidowicz

Доброго здоровья.
Поверьте пожалуста дз.

2021-11-28 22:12 UTC, KirillKulakow commented on model/index.js
>  // const contacts = require('./contacts.json')
удалить

2021-11-28 22:13 UTC, KirillKulakow commented on model/index.js
> +    // .min(3)
три строки с комментариями удалить

2021-11-28 22:13 UTC, KirillKulakow commented on model/index.js
> +    // .email({ minDomainSegments: 2, tlds: { allow: ['com', 'net'] } })
удалить

2021-11-28 22:13 UTC, KirillKulakow commented on model/index.js
> +    // .pattern(/^[0-9]+$/)
две - удалить

2021-11-28 22:13 UTC, KirillKulakow commented on model/index.js
> +// .with('name', 'email', 'phone')
удалить

2021-11-28 22:13 UTC, KirillKulakow commented on model/index.js
> +    // .max(30)
три - удалить

2021-11-28 22:13 UTC, KirillKulakow commented on model/index.js
> +    // .email({ minDomainSegments: 2, tlds: { allow: ['com', 'net'] } })
удалить

2021-11-28 22:13 UTC, KirillKulakow commented on model/index.js
> +    // .length(10)
удалить

2021-11-28 22:16 UTC, KirillKulakow commented on routes/api/contacts.js
> +  console.log('~ delitedContact', delitedContact)
удалить

2021-11-28 22:17 UTC, KirillKulakow commented on routes/api/contacts.js
> +  console.log('~ updatedContact', updatedContact)
удалить

2021-11-28 22:17 UTC, KirillKulakow requested changes
Need fix

2021-12-01 17:27 UTC, Leonidowicz commented on model/index.js
>  // const contacts = require('./contacts.json')
Удалил.

2021-12-01 17:27 UTC, Leonidowicz commented on model/index.js
> +    // .email({ minDomainSegments: 2, tlds: { allow: ['com', 'net'] } })
Удалил.

2021-12-01 17:27 UTC, Leonidowicz commented on model/index.js
> +    // .pattern(/^[0-9]+$/)
Удалил.

2021-12-01 17:27 UTC, Leonidowicz commented on model/index.js
> +// .with('name', 'email', 'phone')
Удалил.

2021-12-01 17:28 UTC, Leonidowicz commented on model/index.js
> +    // .max(30)
Удалил.

2021-12-01 17:28 UTC, Leonidowicz commented on model/index.js
> +    // .email({ minDomainSegments: 2, tlds: { allow: ['com', 'net'] } })
Удалил.

2021-12-01 17:28 UTC, Leonidowicz commented on model/index.js
> +    // .length(10)
Удалил.

2021-12-01 17:28 UTC, Leonidowicz commented on routes/api/contacts.js
> +  console.log('~ delitedContact', delitedContact)
Удалил.

2021-12-01 17:28 UTC, Leonidowicz commented on routes/api/contacts.js
> +  console.log('~ updatedContact', updatedContact)
Удалил.

2021-12-01 17:31 UTC, Leonidowicz commented
Добрый вечер. Удалил консоль-логи и закоментированный код.

2021-12-01 19:47 UTC, KirillKulakow approved these changes

2021-12-04 16:27 UTC, merged